name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build the Python runtime image
        run: docker build . --file Dockerfile --target runtime --tag py311-runtime:${{ github.sha }}
      - name: Export the Docker image
        run: docker save py311-runtime:${{ github.sha }} | gzip > py311-runtime-${{ github.sha }}.tar.gz
      - name: Upload the Docker image
        uses: actions/upload-artifact@v6
        with:
          name: py311-runtime-${{ github.sha }}
          path: py311-runtime-${{ github.sha }}.tar.gz
          compression-level: 0
          retention-days: 7
