name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Build the Python runtime image
        run: docker build . --file Dockerfile --target runtime --tag py311-runtime:${{ github.sha }}
